# Generated by Django 6.0.5 on 2026-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_attendance_breaklog_leavebalance_leaverequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='photo_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
