# Generated by Django 6.0.5 on 2026-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_attendance_check_in_photo_attendance_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
